### ISSUE TITLE
Feature request: Add and support int key for CborPropertyAttribute

### ISSUE THREAD

**Issue by rmja** [dahomey-technologies/Dahomey.Cbor#92]
It would be really useful if the `CborPropertyAttribute` could support an int key similar to the `KeyAttribute` in [MessagePack](https://github.com/neuecc/MessagePack-CSharp#quick-start).

Edit: Mayby this is actually two feature requests:
1. CborProperty(x) should be used in an map object mapping where the key is the integer x.
2. CborKey(x) should be used in an array mapping where x is the array position just like messagepack.

**Comment by mcatanzariti** [comment]
plan:
- add a property `int Index` to `CborPropertyAttribute`
- add a `CborArrayMappingAttribute` to annotate a class. If `CborArrayMappingAttribute`, `CborPropertyAttribute.Index` is interpreted as an index in an array, otherwise it is interpreted as an integer key

**Comment by mcatanzariti** [comment]
Current implementation does not yet support Discriminators nor CreatorMappings.

Supporting Discriminators is tricky, especially for the array format because the number of items in the array for a specific class could be variable if DiscriminatorPolicy is set to Auto. 

One possible implementation is to use a Semantic Tag to identify the discriminator property/field.
Semating Tag [39](https://github.com/lucas-clemente/cbor-specs/blob/master/id.md) could be used for this purpose.
